### ISSUE TITLE
Maintenance Issue

### ISSUE THREAD

**Issue by yoho321** [MGMCN/FastCV#3]
Hi MGMCN,
FastCV is a very good idea, but I think the current version is not good to maintain and extend as the environment changing. So I can contribute a Dockerfile to help control the requirements and environment of this project, so that this project can be maintained and run for a long time.
Regards

**Comment by MGMCN** [comment]
Hi yoho321,

I don't think it's necessary. 

But I don't mind if you write a dockerfile either. 

You can just create a new pull request to contribute.

Regards

**Comment by yoho321** [comment]
# Issue
When I run the shell script in Ubuntu environment on docker , there are some issues as shown below:
```Bash
fastcv  | build-linux-x86_64.sh: line 1: sudo: command not found
fastcv  | build-linux-x86_64.sh: line 2: sudo: command not found
fastcv  | build-linux-x86_64.sh: line 3: sudo: command not found
fastcv  | build-linux-x86_64.sh: line 4: sudo: command not found
fastcv  | build-linux-x86_64.sh: line 6: hugo: command not found
fastcv  | build-linux-x86_64.sh: line 7: git: command not found
fastcv  | cp: cannot stat 'hugoServer/mycv/themes/resume-a4/config.yaml': No such file or directory
fastcv  | cp: cannot stat 'hugoServer/mycv/themes/resume-a4/exampleSite/data': No such file or directory
fastcv  | rm: cannot remove 'hugoServer/mycv/config.toml': No such file or directory
fastcv  | build-linux-x86_64.sh: line 11: hugo: command not found
```
I am not that familiar with docker, so I cannot fix it by myself. I have attached my Dockerfile and docker-compose file, please check.
## Dockerfile
```
FROM ubuntu:23.04

LABEL maintainer="JSHE"

RUN apt update

COPY build-linux-x86_64.sh build-linux-x86_64.sh

CMD ["bash","build-linux-x86_64.sh"]
```
## docker-compose.yml
```yml
version: "3"

services:
  fastcv:
    build: .
    container_name: fastcv
    ports:
    - "5555:5555"
```

**Comment by MGMCN** [comment]
First plz make sure your fork proj is up to date.

**Comment by MGMCN** [comment]
I will call someone to help you! @Kabuda-czh

**Comment by MGMCN** [comment]
Maybe you should run the apt-related commands through the docker run command.
